name: yardsafety
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter
  dotted_border: ^3.1.0
  image_picker: ^1.1.2
  http: ^1.2.1
  dart_pusher_channels: ^1.2.3

  cupertino_icons: ^1.0.8
  circle_nav_bar: ^2.2.0
  shared_preferences: ^2.2.2
  intl: ^0.18.1
 
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/

  